"""Uploaded ``.xlsx`` workbooks, parsed locally with openpyxl (lane B).

**The Sheets API cannot read an uploaded ``.xlsx``.** It has no ``spreadsheetId``,
and ``spreadsheets.get`` on its Drive file id returns 404. The documented
workaround — convert it to a native Sheet with ``files.copy`` — is also closed to
us: converting needs write scope (v1 has none) and the service account's 0 GB
storage quota makes ``files.copy`` fail with ``storageQuotaExceeded`` unless the
copy is parented into a shared drive (SPEC §4.7). So the supported path is the one
implemented here: download the bytes, parse them in-process.

Design constraints, each with a failure it prevents:

* ``read_only=True`` — streams the sheet instead of materializing an object graph
  per cell. Without it a 2.6 MB workbook becomes hundreds of megabytes of Python
  objects inside an Odoo worker.
* ``data_only=True`` — returns the value Excel last cached for a formula cell.
  It returns ``None`` when the file was never recalculated by Excel (the usual
  cause: it was generated by a library, or edited and saved by a tool that does
  not evaluate formulas). Reading that ``None`` as an empty cell would write NULL
  over real data, so those cells are detected and reported as
  ``XLSX_NO_CACHED_VALUES`` and the row is quarantined instead.
* Legacy ``.xls`` (BIFF) is **rejected**, not attempted. openpyxl reads only
  OOXML; v1 does not ship ``xlrd``. The node is recorded and skipped with
  ``unsupported_mime`` so its existence stays auditable.

The returned tab dicts use the **same key set** as
:class:`~.sheets_reader.SheetsReader`, so lane D stages a native Google Sheet and
an uploaded workbook through exactly one code path. The two differences are
carried in the data, not in the shape: ``source_kind`` is ``'xlsx'``, and
``sheet_gid`` is the negative surrogate ``-(1 + worksheet_index)`` because an xlsx
worksheet has no stable gid of its own.
"""

from __future__ import annotations

import datetime as _dt
import io
import logging
from decimal import Decimal as _Decimal
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

from .errors import (
    CODE_MISSING_DEPENDENCY,
    CODE_TOO_LARGE,
    CODE_UNSUPPORTED_MIME,
    CODE_XLSX_NO_CACHED_VALUES,
    CODE_XLSX_SCAN_INCOMPLETE,
    CODE_XLSX_TAB_AMBIGUOUS,
    GDrivePermanentError,
)
from .sheets_reader import SHEET_TYPE_GRID, a1_ref, column_letter, quote_title

_logger = logging.getLogger(__name__)

__all__ = [
    'XlsxReader',
    'gid_for_index',
    'index_for_gid',
    'jsonable',
    'ZIP_MAGIC',
    'OLE2_MAGIC',
    'DEFAULT_MAX_ROWS',
    'DEFAULT_MAX_COLUMNS',
    'MAX_FORMULA_POSITIONS',
]

#: An OOXML workbook is a ZIP container.
ZIP_MAGIC = b'PK\x03\x04'

#: A legacy ``.xls`` (and an encrypted OOXML file) is an OLE2 compound document.
#: Sniffing the magic gives a precise, actionable error instead of openpyxl's
#: generic ``InvalidFileException``, which sends people looking for a corrupt
#: download that never happened.
OLE2_MAGIC = b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1'

#: Safety ceilings. A worksheet with a corrupt ``dimension`` record, or one that a
#: tool padded to the format maximum (1 048 576 × 16 384), would otherwise be
#: materialized in full inside an Odoo worker.
DEFAULT_MAX_ROWS = 500000
DEFAULT_MAX_COLUMNS = 2048

#: Cap on tracked formula positions per workbook, so a spreadsheet that is 95 %
#: formulas cannot turn detection into a memory problem. Beyond the cap the sheet
#: is flagged wholesale rather than cell by cell — less precise, never less safe.
MAX_FORMULA_POSITIONS = 200000


def gid_for_index(worksheet_index: int) -> int:
    """Return the surrogate ``sheet_gid`` for a 0-based worksheet index.

    ``-(1 + index)``, so index 0 → ``-1``, index 1 → ``-2`` (SPEC §3.5). It is
    **negative on purpose**: native Google Sheets gids are non-negative, and gid 0
    is a perfectly ordinary native gid, so a non-negative surrogate would collide
    with a real one the day a workbook is converted from xlsx to a native Sheet.
    """
    index = int(worksheet_index)
    if index < 0:
        raise ValueError('worksheet index must be >= 0, got %r' % (worksheet_index,))
    return -(1 + index)


def _scan_gap_for(scan_gap: Optional[dict], title: str) -> Optional[dict]:
    """Return ``scan_gap`` when it applies to worksheet ``title``, else ``None``.

    ``titles=None`` means the whole workbook is affected (the pre-scan itself
    failed); a set means only those worksheets were left unscanned.
    """
    if not scan_gap:
        return None
    titles = scan_gap.get('titles')
    if titles is None or title in titles:
        return scan_gap
    return None


def index_for_gid(sheet_gid: int) -> int:
    """Inverse of :func:`gid_for_index`. Raises for a non-surrogate gid."""
    gid = int(sheet_gid)
    if gid >= 0:
        raise ValueError('%r is a native Sheets gid, not an xlsx surrogate' % (sheet_gid,))
    return -gid - 1


def jsonable(value: Any) -> Any:
    """Coerce one openpyxl cell value into something ``fields.Json`` can store.

    openpyxl hands back native ``datetime``/``date``/``time``/``timedelta`` and
    ``Decimal`` objects, none of which survive JSON serialization. Lane D writes
    every cell into ``gdrive.staged.row.payload``, so it needs this on the payload
    path.

    It is deliberately **not** applied to the ``rows`` this module returns.
    Canonicalization must see the original typed value: lane C's ``DATE_CANON``
    recognises a real ``date`` object and emits ``d:2026-07-31`` from it directly,
    whereas from the string ``"2026-07-31 00:00:00"`` it would have to re-parse
    against the column's declared formats and would emit ``e:BAD_DATE`` whenever
    they did not match. Stringify for storage; canonicalize from the original.
    """
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, _dt.datetime):
        return value.isoformat(sep=' ')
    if isinstance(value, _dt.date):
        return value.isoformat()
    if isinstance(value, _dt.time):
        return value.isoformat()
    if isinstance(value, _dt.timedelta):
        return value.total_seconds()
    if isinstance(value, _Decimal):
        return format(value, 'f')
    if isinstance(value, bytes):
        return value.decode('utf-8', 'replace')
    return str(value)


def _is_formula(value: Any) -> bool:
    """True when a ``data_only=False`` read returned a formula rather than a value.

    Covers the two shapes openpyxl uses: a plain ``str`` starting with ``=`` (the
    normal case, and the only one ``read_only`` mode produces), and the
    ``ArrayFormula`` / ``DataTableFormula`` wrapper objects it introduced for
    dynamic arrays. The wrappers are matched by class name so this module does not
    import openpyxl internals that move between releases.
    """
    if isinstance(value, str):
        return value.startswith('=')
    return type(value).__name__ in {'ArrayFormula', 'DataTableFormula'}


def _reset_dimensions(worksheet: Any) -> None:
    """Make openpyxl derive a worksheet's extent from its cells, not its header.

    An ``.xlsx`` carries a ``<dimension>`` record announcing the used range, and
    plenty of generators write it wrong — Google's own xlsx export and several
    reporting libraries among them. In ``read_only`` mode openpyxl trusts that
    record, so a **too-small** dimension silently truncates the read: rows that
    exist in the file are never yielded, the tab looks shorter than it is, and the
    missing rows present downstream as deleted. ``reset_dimensions()`` is
    openpyxl's own documented remedy (it clears the cached extent so iteration
    scans the actual cells).

    Guarded on both sides: the method is only called when it exists and is
    callable (it is a method in openpyxl 3.x but has changed shape historically),
    and any failure is logged and ignored, because falling back to the declared
    dimension is strictly better than failing the whole workbook.
    """
    resetter = getattr(worksheet, 'reset_dimensions', None)
    if not callable(resetter):
        return
    try:
        resetter()
    except Exception as exc:  # pragma: no cover - openpyxl version dependent
        _logger.debug('reset_dimensions() failed for worksheet %r: %s',
                      getattr(worksheet, 'title', '?'), exc)


def _frozen_rows(worksheet: Any) -> int:
    """Count the frozen header rows, so the shape matches the Sheets side.

    ``freeze_panes`` is the top-left *unfrozen* cell (``'A2'`` means one frozen
    row), which is why this subtracts one. Advisory only: lane D takes
    ``header_row`` from the dataset contract, never from a formatting hint. It is
    surfaced because it is a good default suggestion in the mapping builder, and a
    bad thing to silently rely on.
    """
    reference = getattr(worksheet, 'freeze_panes', None)
    if not isinstance(reference, str) or not reference:
        return 0
    digits = ''.join(char for char in reference if char.isdigit())
    if not digits:
        return 0
    try:
        return max(0, int(digits) - 1)
    except ValueError:  # pragma: no cover - digits is guaranteed numeric here
        return 0


def _is_blank(value: Any) -> bool:
    """True for a cell that carries nothing.

    ``None`` (openpyxl's empty cell) and ``''`` are treated identically, matching
    the Sheets side where an interior empty is ``''`` and a trailing empty is
    simply absent. Note ``0``, ``False`` and ``0.0`` are **not** blank — that
    distinction is why this is a function and not a truthiness test.
    """
    return value is None or value == ''


class XlsxReader:
    """Parse an in-memory ``.xlsx``/``.xlsm`` workbook into the shared tab shape.

    :param logger: injected logger; defaults to this module's.
    :param max_rows: refuse a worksheet with more rows than this.
    :param max_columns: refuse a worksheet wider than this.
    :param detect_uncached: when True (default) the workbook is parsed a second
        time with ``data_only=False`` so formula cells with no cached value can be
        distinguished from genuinely empty cells. Disable only when the caller has
        another reason to trust the file; the cost of the extra parse is small
        next to the cost of reading a broken formula as an empty cell.

    Stateless between calls apart from counters, so one instance may read many
    workbooks. It performs **no network I/O at all** — the bytes arrive from
    :class:`~.drive_download.DriveDownloader`.
    """

    def __init__(
        self,
        logger: Optional[logging.Logger] = None,
        max_rows: int = DEFAULT_MAX_ROWS,
        max_columns: int = DEFAULT_MAX_COLUMNS,
        detect_uncached: bool = True,
    ) -> None:
        self.log = logger or _logger
        self.max_rows = int(max_rows or DEFAULT_MAX_ROWS)
        self.max_columns = int(max_columns or DEFAULT_MAX_COLUMNS)
        self.detect_uncached = bool(detect_uncached)
        self.workbooks_read = 0
        self.tabs_read = 0
        self.rows_read = 0
        self.uncached_cells = 0

    # -- guards ------------------------------------------------------------ #

    @staticmethod
    def _require_openpyxl() -> Any:
        """Import openpyxl, or fail with a message that names the fix.

        openpyxl ships with Odoo, so this only fires on a stripped environment —
        exactly the case where a generic ``ImportError`` deep inside a cron would
        be attributed to this module rather than to the missing dependency.
        """
        try:  # pragma: no cover - environment dependent
            import openpyxl

            return openpyxl
        except Exception as exc:  # pragma: no cover
            raise GDrivePermanentError(
                'openpyxl is not installed, so uploaded .xlsx workbooks cannot be '
                'parsed. It is part of Odoo\'s own requirements.txt; reinstall the '
                'Python dependencies for this instance.',
                code=CODE_MISSING_DEPENDENCY,
            ) from exc

    @staticmethod
    def _reject_unsupported(data: bytes) -> None:
        """Refuse anything that is not an OOXML workbook, with a precise reason."""
        head = bytes(data or b'')[:8]
        if head.startswith(OLE2_MAGIC):
            raise GDrivePermanentError(
                'This file is an OLE2 compound document — a legacy .xls workbook, or '
                'a password-protected .xlsx. openpyxl reads only the OOXML format and '
                'v1 does not ship xlrd. Ask the owner to re-save it as .xlsx '
                '(unprotected); the node is recorded and skipped, not lost.',
                code=CODE_UNSUPPORTED_MIME,
            )
        if not head.startswith(ZIP_MAGIC):
            raise GDrivePermanentError(
                'This file is not an OOXML workbook (no ZIP container signature). '
                'Drive reported a spreadsheet MIME type, so either the upload is '
                'corrupt or the MIME type is wrong.',
                code=CODE_UNSUPPORTED_MIME,
            )

    def _check_extent(self, title: str, rows: int, columns: int) -> None:
        if rows > self.max_rows:
            raise GDrivePermanentError(
                'Worksheet %r has %d rows, above the %d-row safety limit for local '
                'parsing.' % (title, rows, self.max_rows),
                code=CODE_TOO_LARGE,
                details={'tab_title': title, 'rows': rows, 'limit': self.max_rows},
            )
        if columns > self.max_columns:
            raise GDrivePermanentError(
                'Worksheet %r is %d columns wide, above the %d-column safety limit '
                'for local parsing.' % (title, columns, self.max_columns),
                code=CODE_TOO_LARGE,
                details={'tab_title': title, 'columns': columns, 'limit': self.max_columns},
            )

    # -- the read ---------------------------------------------------------- #

    def read(self, data: bytes) -> List[dict]:
        """Parse ``data`` and return one dict per worksheet, in workbook order.

        :param data: the raw bytes of the ``.xlsx``, straight from
            ``files.get_media``.
        :returns: a list of tab dicts with the shared shape::

                {'source_kind': 'xlsx', 'sheet_gid': -1, 'tab_title': 'Cashflow',
                 'tab_index': 0, 'hidden': False, 'sheet_type': 'GRID',
                 'grid_rows': 2411, 'grid_cols': 13, 'frozen_rows': 1,
                 'rows': [[...], ...],          # rectangular, right-padded
                 'row_count': 2411, 'col_count': 13,
                 'used_range': "'Cashflow'!A1:M2411",
                 'read_complete': True,
                 'warnings': [{'code','message'}],
                 'error_cells': [{'row','col','a1','code','message'}]}

        ``read_complete`` is False for any worksheet containing a formula cell
        with no cached value. Lane D ANDs it into ``gdrive.dataset
        .last_read_complete``, which is the gate SPEC §9.6 uses to forbid the
        delete planner from running — so an unreadable cell disarms deletions for
        that dataset instead of silently presenting as an empty one.

        :raises GDrivePermanentError: for legacy ``.xls``, encrypted or corrupt
            files, and worksheets beyond the extent limits. The ``code`` maps onto
            ``gdrive.node.skip_reason``.
        """
        openpyxl = self._require_openpyxl()
        self._reject_unsupported(data)

        if self.detect_uncached:
            formula_positions, scan_gap = self._formula_positions(openpyxl, data)
        else:
            # Detection deliberately switched off by the caller; that is an
            # explicit opt-out, not an undetected gap.
            formula_positions, scan_gap = {}, None

        try:
            workbook = openpyxl.load_workbook(
                io.BytesIO(data), read_only=True, data_only=True,
            )
        except GDrivePermanentError:
            raise
        except Exception as exc:  # noqa: BLE001 - re-raised as a typed error
            raise GDrivePermanentError(
                'openpyxl could not open this workbook: %s' % exc,
                code=CODE_UNSUPPORTED_MIME,
            ) from exc

        tabs: List[dict] = []
        try:
            for index, worksheet in enumerate(workbook.worksheets):
                tabs.append(self._read_worksheet(
                    worksheet, index, formula_positions.get(worksheet.title) or set(),
                    scan_gap=_scan_gap_for(scan_gap, worksheet.title),
                ))
        finally:
            # read_only workbooks hold an open ZIP handle; leaking it inside a
            # long-lived cron worker leaks file descriptors one workbook at a time.
            try:
                workbook.close()
            except Exception:  # pragma: no cover - close() is best effort
                self.log.debug('Closing the openpyxl workbook raised; ignoring.')

        self.workbooks_read += 1
        self.log.info(
            'Parsed xlsx workbook: %d worksheet(s), %d row(s), %d uncached formula cell(s).',
            len(tabs), sum(t['row_count'] for t in tabs),
            sum(len(t['error_cells']) for t in tabs),
        )
        return tabs

    def _read_worksheet(
        self, worksheet: Any, index: int, formula_cells: Set[Tuple[int, int]],
        scan_gap: Optional[dict] = None,
    ) -> dict:
        """Materialize one worksheet into the shared tab shape.

        :param scan_gap: set when the formula pre-scan did not cover this
            worksheet. The worksheet is then reported ``read_complete=False``
            with a sheet-level warning: uncached formula cells may be present
            and undetected, and a workbook whose formulas we could not see must
            never be indistinguishable from one that has none.
        """
        title = worksheet.title or ''
        _reset_dimensions(worksheet)
        raw_rows: List[Tuple] = []
        width = 0
        last_content_row = -1

        for row_index, row in enumerate(worksheet.iter_rows(values_only=True)):
            if row_index >= self.max_rows:
                self._check_extent(title, row_index + 1, width)
            row = tuple(row or ())
            if len(row) > self.max_columns:
                self._check_extent(title, row_index + 1, len(row))
            # Effective width ignores trailing blanks, mirroring the Sheets API,
            # which drops them. Sizing from `ws.max_column` instead would inherit
            # the file's `dimension` record — routinely wrong, and wrong in the
            # expensive direction (16 384 columns of nothing).
            effective = len(row)
            while effective and _is_blank(row[effective - 1]):
                effective -= 1
            if effective:
                width = max(width, effective)
                last_content_row = row_index
            raw_rows.append(row)

        # Drop trailing all-blank rows for the same reason.
        raw_rows = raw_rows[:last_content_row + 1]
        self._check_extent(title, len(raw_rows), width)

        rows: List[List[Any]] = []
        error_cells: List[dict] = []
        for row_index, row in enumerate(raw_rows):
            padded: List[Any] = []
            for col_index in range(width):
                value = row[col_index] if col_index < len(row) else None
                if value is None and (row_index, col_index) in formula_cells:
                    # A formula whose cached value Excel never wrote. Reported,
                    # never read as empty: `data_only` cannot compute it and this
                    # process must not guess (SPEC §4.7).
                    error_cells.append({
                        'row': row_index,
                        'col': col_index,
                        'a1': a1_ref(title, row_index + 1, col_index),
                        'code': CODE_XLSX_NO_CACHED_VALUES,
                        'message': 'Formula cell has no cached value; the workbook was '
                                   'never recalculated by Excel.',
                    })
                padded.append('' if value is None else value)
            rows.append(padded)

        warnings: List[dict] = []
        if error_cells:
            self.uncached_cells += len(error_cells)
            warnings.append({
                'code': CODE_XLSX_NO_CACHED_VALUES,
                'message': 'Worksheet %r has %d formula cell(s) with no cached value. '
                           'Open the workbook in Excel, recalculate and re-save, or map '
                           'those columns to a source that carries values.'
                           % (title, len(error_cells)),
            })
            self.log.warning(
                'xlsx worksheet %r: %d formula cell(s) had no cached value; the read is '
                'not complete and deletions stay disarmed for this dataset.',
                title, len(error_cells),
            )

        if scan_gap is not None:
            warnings.append({
                'code': CODE_XLSX_SCAN_INCOMPLETE,
                'message': 'Worksheet %r: %s Uncached formula cells cannot be ruled out, '
                           'so this read is reported incomplete and deletions stay '
                           'disarmed for the dataset.' % (title, scan_gap['message']),
            })
            self.log.warning(
                'xlsx worksheet %r was not covered by the formula pre-scan (%s); '
                'reporting read_complete=False.', title, scan_gap['message'],
            )

        self.tabs_read += 1
        self.rows_read += len(rows)
        return {
            'source_kind': 'xlsx',
            'sheet_gid': gid_for_index(index),
            'tab_title': title,
            'tab_index': index,
            # openpyxl exposes 'visible' / 'hidden' / 'veryHidden'.
            'hidden': (getattr(worksheet, 'sheet_state', 'visible') or 'visible') != 'visible',
            # xlsx has exactly one kind of worksheet as far as this system cares;
            # the key exists so the shape matches the Sheets side.
            'sheet_type': SHEET_TYPE_GRID,
            'grid_rows': len(rows),
            'grid_cols': width,
            'frozen_rows': _frozen_rows(worksheet),
            'rows': rows,
            'row_count': len(rows),
            'col_count': width,
            'used_range': self.used_range(title, len(rows), width),
            'read_complete': not error_cells and scan_gap is None,
            'warnings': warnings,
            'error_cells': error_cells,
        }

    def _formula_positions(
        self, openpyxl: Any, data: bytes
    ) -> Tuple[Dict[str, Set[Tuple[int, int]]], Optional[dict]]:
        """Locate every formula cell, keyed by worksheet title.

        A second streaming parse with ``data_only=False``, run **before** the value
        parse so that only formula positions — normally a small minority of cells —
        are held in memory, rather than every blank cell as a candidate.

        :returns: ``(positions, scan_gap)``. ``scan_gap`` is ``None`` when the
            whole workbook was scanned, otherwise
            ``{'message': str, 'titles': set|None}`` naming the worksheets whose
            formula detection is unreliable (``titles=None`` meaning *all* of
            them). :meth:`read` turns that into ``read_complete=False`` plus a
            sheet-level warning on each affected worksheet.

            **This return value is load-bearing.** ``read_complete`` is the gate
            SPEC §9.6 uses to forbid the delete planner from running. Both gap
            paths below previously returned a partial-or-empty dict that was
            indistinguishable from "this workbook contains no formulas", so
            every affected worksheet was reported as a fully complete read while
            its uncached formula cells staged as ``''`` — the mechanism that
            disarms deletions silently disarming itself.

        Known limitation, stated because silence here would be dishonest: in
        ``read_only`` mode openpyxl reports the formula text only for the master
        cell of a *shared* formula group; the dependent cells read as ``None`` in
        both passes and are therefore indistinguishable from blanks. Those cells
        stage as empty. The mitigation is the sheet-level warning raised whenever
        *any* uncached formula is found in the worksheet, which is enough to make
        an operator look at the file.
        """
        positions: Dict[str, Set[Tuple[int, int]]] = {}
        try:
            workbook = openpyxl.load_workbook(io.BytesIO(data), read_only=True, data_only=False)
        except Exception as exc:  # noqa: BLE001
            # Not fatal on its own: the value pass will produce its own, better
            # error if the file is truly unreadable. A workbook that opens fine
            # with data_only=True but trips openpyxl here (a defined name, a
            # chart, a pivot construct parsed only in the non-data_only path) is
            # readable — but its formulas are invisible to us, so every
            # worksheet is reported incomplete rather than clean.
            self.log.warning(
                'Could not pre-scan the workbook for formulas (%s); uncached formula '
                'cells cannot be detected in this read.', exc,
            )
            return positions, {
                'message': 'the formula pre-scan failed (%s).' % exc,
                'titles': None,
            }

        total = 0
        capped_from: Optional[str] = None
        scanned: Set[str] = set()
        try:
            for worksheet in workbook.worksheets:
                if capped_from is not None:
                    continue
                _reset_dimensions(worksheet)
                found: Set[Tuple[int, int]] = set()
                for row_index, row in enumerate(worksheet.iter_rows(values_only=True)):
                    for col_index, value in enumerate(row or ()):
                        if _is_formula(value):
                            found.add((row_index, col_index))
                            total += 1
                    if total >= MAX_FORMULA_POSITIONS:
                        self.log.warning(
                            'Workbook exceeds the %d tracked-formula limit at worksheet '
                            '%r; per-cell uncached detection stops here and every '
                            'worksheet from this one on is flagged wholesale.',
                            MAX_FORMULA_POSITIONS, worksheet.title,
                        )
                        break
                if found:
                    positions[worksheet.title] = found
                if total >= MAX_FORMULA_POSITIONS:
                    # This worksheet was cut off mid-scan, so it is *not*
                    # scanned; neither is anything after it.
                    capped_from = worksheet.title
                else:
                    scanned.add(worksheet.title)
            titles = None
            if capped_from is not None:
                titles = {w.title for w in workbook.worksheets} - scanned
        finally:
            try:
                workbook.close()
            except Exception:  # pragma: no cover - close() is best effort
                self.log.debug('Closing the formula-scan workbook raised; ignoring.')

        if capped_from is None:
            return positions, None
        return positions, {
            'message': 'the %d tracked-formula cap was reached at worksheet %r, so this '
                       'worksheet was not fully scanned.' % (MAX_FORMULA_POSITIONS, capped_from),
            'titles': titles,
        }

    # -- helpers used by lane D ------------------------------------------- #

    @staticmethod
    def used_range(title: str, row_count: int, col_count: int) -> str:
        """Build the ``used_range`` string in the same spelling Sheets returns.

        ``'Cashflow'!A1:M2411``. An empty worksheet yields ``'Title'!A1:A1`` rather
        than an empty string, so ``gdrive.dataset.used_range`` is always a valid A1
        range that a human can paste.
        """
        if row_count <= 0 or col_count <= 0:
            return '%s!A1:A1' % quote_title(title)
        return '%s!A1:%s%d' % (quote_title(title), column_letter(col_count - 1), row_count)

    @staticmethod
    def match_tab(
        tabs: Sequence[dict],
        tab_title: str,
        tab_index: Optional[int] = None,
    ) -> dict:
        """Re-identify a previously seen worksheet in a freshly parsed workbook.

        WHY this is hard, and why it gets its own function: an xlsx worksheet has
        **no stable identifier**. A native Google Sheet tab keeps its numeric gid
        across renames, so a rename is provably a rename. In xlsx, a renamed
        worksheet and a deleted-then-created worksheet are the same bytes at the
        same index, and guessing wrong means either dropping a dataset's history or
        attaching one tab's rows to another tab's dataset.

        The resolution order is title first, then index (SPEC §4.7):

        * **title** — exact match wins; a case/whitespace-insensitive match is
          accepted next, and reported so a rename is visible.
        * **index** — same position in the workbook. Accepted, and reported, since
          this is where a genuine rename lands.
        * **neither** — ``XLSX_TAB_AMBIGUOUS``. Blocking: the caller must stop the
          dataset rather than pick something.

        :returns: ``{'tab': dict|None, 'strategy': 'title'|'title_fuzzy'|'index'|
            'none', 'code': None|'XLSX_TAB_AMBIGUOUS', 'message': str}``. A missing
            match is returned, not raised, because it is a data condition the
            caller records on the dataset — not a transport failure.
        """
        candidates = list(tabs or [])
        wanted = tab_title or ''

        for tab in candidates:
            if (tab.get('tab_title') or '') == wanted:
                return {'tab': tab, 'strategy': 'title', 'code': None,
                        'message': 'Matched worksheet by exact title.'}

        normalized = ' '.join(wanted.split()).casefold()
        fuzzy = [t for t in candidates
                 if ' '.join((t.get('tab_title') or '').split()).casefold() == normalized]
        if len(fuzzy) == 1:
            return {
                'tab': fuzzy[0], 'strategy': 'title_fuzzy', 'code': None,
                'message': 'Matched worksheet %r to %r ignoring case and spacing.'
                           % (wanted, fuzzy[0].get('tab_title')),
            }

        if tab_index is not None:
            by_index = [t for t in candidates if t.get('tab_index') == tab_index]
            if len(by_index) == 1:
                return {
                    'tab': by_index[0], 'strategy': 'index', 'code': None,
                    'message': 'Worksheet %r was not found; matched position %d, now '
                               'titled %r. Treating this as a rename, not a deletion.'
                               % (wanted, tab_index, by_index[0].get('tab_title')),
                }

        return {
            'tab': None, 'strategy': 'none', 'code': CODE_XLSX_TAB_AMBIGUOUS,
            'message': 'Worksheet %r is gone and position %s does not resolve to a '
                       'single worksheet. An .xlsx worksheet carries no stable id, so '
                       'a rename cannot be told apart from a delete-and-create; the '
                       'dataset is blocked pending a human decision.'
                       % (wanted, tab_index),
        }

    @staticmethod
    def jsonable_rows(rows: Iterable[Sequence[Any]]) -> List[List[Any]]:
        """Apply :func:`jsonable` across a grid, for ``gdrive.staged.row.payload``.

        Call this on the way into storage only. Canonicalization must run against
        the original rows — see the note on :func:`jsonable`.
        """
        return [[jsonable(cell) for cell in row] for row in rows]

    def stats(self) -> dict:
        """Counters for ``gdrive.sync.run``. No network is involved, so there are
        no quota units to report — only what was parsed."""
        return {
            'workbooks_read': self.workbooks_read,
            'tabs_read': self.tabs_read,
            'rows_read': self.rows_read,
            'uncached_cells': self.uncached_cells,
        }
